---
title: "BI588M6"
author: "Author: Lia"
date: "Date: 2023-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(curl)
```

### Challenge 1

```{r}
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/Country-Data-2016.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
```

```{r}
summary(d)
names(d)
```

```{r}
d$density <- d$population/d$area
d <- d[order(-d$density), ]
d[1:10, ]
```

```{r}
d <- d[order(d$density), ]
d[1:10, ]
```

```{r}
new <- d[grep("^[A-F]", d$country), ]
summary(new)
mean(new$population, na.rm=TRUE)
mean(new$area, na.rm=TRUE)
```

### Challenge 2

```{r}
par(mfrow = c(2, 3))
boxplot(d$population)
boxplot(log(d$population))
boxplot(d$area)
boxplot(log(d$area))
barplot(d$population)
barplot(d$area)
```

### Challenge 3

```{r}
par(mfrow = c(1, 2))  # gives us two panels
attach(d)
hist(log(population), freq = FALSE, col = "red", main = "Plot 1", xlab = "log(population size)",
    ylab = "density", ylim = c(0, 0.2))
lines(density(log(population), na.rm=TRUE), col= "blue")
hist(log(area), freq = FALSE, col = "cyan", main = "Plot 2", xlab = "log(area)",
    ylab = "density", ylim = c(0, 0.2))
lines(density(log(population), na.rm=TRUE), col= "purple")
```

```{r}
par(mfrow = c(1, 1))  # set up one panel and redraw the log(population) histogram
hist(log(population), freq = FALSE, col = "white", main = "My Plot with Mean and Density",
    xlab = "log(population size)", ylab = "density", ylim = c(0, 0.2))
abline(v = mean(log(population), na.rm = TRUE), col = "blue")
lines(density(log(population), na.rm = TRUE), col = "green")
detach(d)
```

### Challenge 4

```{r}
sort(table(d$govt_form), decreasing = TRUE)
```

### Challenge 5

```{r}
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/KamilarAndCooperData.csv")
d <- read.csv(f, header = TRUE, stringsAsFactors = FALSE)
attach(d)
head(d)
summary(d)
boxplot(log(Body_mass_female_mean) ~ Family, d)
detach(d)
```

```{r}
library(ggplot2)
p <- ggplot(data = d, aes(x = Family, y = log(Body_mass_female_mean)))  #define the variables
p <- p + geom_boxplot()  #graph them in a boxplot
p <- p + theme(axis.text.x = element_text(angle = 90))  #put x-axis names at 90deg
p <- p + ylab("log(Female Body Mass)")  #rename y-axis title
p  #show me the graph
```

### Challenge 6

```{r}
attach(d)
par(mfrow = c(1, 2))
plot(x = Body_mass_female_mean, y = Brain_Size_Female_Mean)
plot(x = log(Body_mass_female_mean), y = log(Brain_Size_Female_Mean))
detach(d)
```

```{r}
p <- ggplot(data = d, aes(x = log(Body_mass_female_mean), y = log(Brain_Size_Female_Mean),
    color = factor(Family)))  # first, we build a plot object and color points by Family
p <- p + xlab("log(Female Body Mass)") + ylab("log(Female Brain Size)")  # then we modify the axis labels
p <- p + geom_point()  # then we make a scatterplot
p <- p + theme(legend.position = "bottom", legend.title = element_blank())  # then we modify the legend
p  # and, finally, we plot the object
```

```{r}
p <- p + facet_wrap(~Family, ncol = 4)
p <- p + theme(legend.position = "none")
p
```

```{r}
p <- p + geom_smooth(method = "lm", fullrange = TRUE)
p
```

### Challenge 7

```{r}
p <- ggplot(data = d, aes(x = log(Body_mass_female_mean), y = log(MaxLongevity_m)))
p <- p + geom_point()
p <- p + geom_smooth(method = "lm")
p
```

```{r}
aggregate(d$Body_mass_female_mean ~ d$Family, FUN = "mean", na.rm = TRUE)
```

```{r}
aggregate(x = d["Body_mass_female_mean"], by = d["Family"], FUN = "mean", na.rm = TRUE)
```

```{r}
library(dplyr)
s <- filter(d, Family == "Hominidae" & Mass_Dimorphism > 2)
head(s)  # filtering a data frame for certain rows...
```

```{r}
s <- arrange(d, Family, Genus, Body_mass_male_mean)  # rearranging a data frame...
head(s)
s <- select(d, Family, Genus, Body_mass_male_mean)  # selecting specific columns...
head(s)
s <- rename(d, Female_Mass = Body_mass_female_mean)
head(s$Female_Mass)  # renaming columns...
s <- mutate(d, Binomial = paste(Genus, Species, sep = " "))
head(s$Binomial)  # and adding new columns...
s <- summarise(d, avgF = mean(Body_mass_female_mean, na.rm = TRUE), avgM = mean(Body_mass_male_mean,
    na.rm = TRUE))
s
byFamily <- group_by(d, Family)
byFamily
s <- summarise(byFamily, avgF = mean(Body_mass_female_mean, na.rm = TRUE), avgM = mean(Body_mass_male_mean,
    na.rm = TRUE))
s
```

```{r}
s <- d %>%                                                          #take dataframe "d"
  group_by(Family) %>%                                           #Group it by Family
  summarise(avgF = mean(Body_mass_female_mean, na.rm=TRUE),      #And calculate mean male BM
            avgM = mean(Body_mass_male_mean, na.rm=TRUE))        #And mean female BM
s
```

### Challenge 8

```{r}
s <- d %>%
    mutate(Binomial = paste(Genus, Species, sep = " ")) %>%
    select(Binomial, Body_mass_female_mean, Body_mass_male_mean, Mass_Dimorphism) %>%
    group_by(Binomial) %>%
    summarise(avgF = mean(Body_mass_female_mean, na.rm = TRUE), avgM = mean(Body_mass_male_mean,
        na.rm = TRUE), avgBMD = mean(Mass_Dimorphism, na.rm = TRUE))
s
```
